services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: "lab"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "25812581"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "lab"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  frontend:
    build:
        context: frontend/.
        dockerfile: Dockerfile
    ports:
        - "3000:3000"
  backend:
    build:
        context: backend/.
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    restart: on-failure
    depends_on:
      - postgres
    links: 
        - postgres
   
 
volumes:
  pgdata: