CREATE TABLE IF NOT EXISTS MathResult (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hash BIGINT  NOT NULL,
    x DOUBLE NOT NULL,
    y DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text TEXT NOT NULL,
    ts TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);